name: rl4finance
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - scipy>=1.10.0
  - requests>=2.28.0
  - pandas>=1.5.0
  - pytorch
  - pip>=21.0
  - pip:
    - python-dotenv>=1.0.0
    - tqdm>=4.65.0
    - -e .
